# Generated by Django 4.0.7 on 2023-06-07 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=250, verbose_name='car name')),
                ('car_color', models.CharField(max_length=50, verbose_name='car color name')),
                ('number_of_cylinder', models.PositiveIntegerField(verbose_name='number of cylinder')),
                ('engine_volume', models.PositiveIntegerField(verbose_name='engine volume')),
                ('number_of_passangers', models.PositiveIntegerField(verbose_name='number of passangers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
