# Generated by Django 4.0.7 on 2023-06-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(verbose_name='engine volume'),
        ),
    ]
